Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
    end
    config.vm.define "prometheus" do |prometheus|
        prometheus.vm.network "private_network", ip: "192.168.33.15"
        prometheus.vm.provision "shell", path: "./install-prometheus.sh"
        prometheus.vm.provision "shell", path: "./install-node_exporter.sh"
    end
    config.vm.define "grafana" do |grafana|
        grafana.vm.network "private_network", ip: "192.168.33.10"
        grafana.vm.provision "shell", path: "./install-node_exporter.sh"
        grafana.vm.provision "shell", path: "./install-grafana.sh"
    end
end
