Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
    end
    config.vm.define "elastic" do |elastic|
        elastic.vm.network "private_network", ip: "192.168.33.15"
        elastic.vm.provision "shell", path: "./install-repo.sh"
        elastic.vm.provision "shell", path: "./install-elasticsearch.sh"
        elastic.vm.provision "shell", path: "./install-kibana.sh"
        elastic.vm.provision "shell", path: "./install-journalbeat.sh"
    end   
end
