Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
    end
    config.vm.define "mysql" do |mysql|
        mysql.vm.network "private_network", ip: "192.168.33.15"
        mysql.vm.provision "shell", path: "./install-mysql.sh"
    end
    # config.vm.define "wordpress" do |wordpress|
    #     wordpress.vm.network "private_network", ip: "192.168.33.10"
    #     wordpress.vm.provision "shell", inline: "apt-get update && \
    #     apt-get -y install apache2 php php-mysql && systemctl enable apache2 && \
    #     rm -f /var/www/html/index.html && chown -R vagrant: /var/www/html"
    #     wordpress.vm.provision "file", source: "index.php", destination: "/var/www/html/index.php"
    #     wordpress.vm.provision "shell", inline: "systemctl restart apache2"
    # end
end
