Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
    end
    config.vm.define "mysql" do |mysql|
        mysql.vm.network "private_network", ip: "192.168.33.15"
        mysql.vm.provision "shell", path: "./install-mysql.sh"
    end
    config.vm.define "wordpress" do |wordpress|
        wordpress.vm.network "private_network", ip: "192.168.33.10"
        wordpress.vm.provision "shell", path: "./install-wordpress.sh"       
    end
end
