Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
    end
    config.vm.define "jenkins" do |jenkins|
        jenkins.vm.network "private_network", ip: "192.168.33.15"
        jenkins.vm.provision "shell", path: "./install-jenkins.sh"
    end   
end
